baseURL = "https://faizmokhtar.com/"
languageCode = "en-us"
title = "til"
theme = "hugo-theme-hello-friend"
paginate = "8"
disqusShortname = "faizmokhtar"
googleAnalytics = "UA-45192347-5"

[Author]
    name = "Faiz Mokhtar"
    bio = "Hi I'm Faiz. I m a software engineer that's currently based in Malaysia. I specialized in iOS development and mobile app CI/CD. I am not actively looking right now but I'm open for new opportunities."
    avatar = "https://s.gravatar.com/avatar/12b7c902b4ef0620c2fd38ef9f4a4510?s=200"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "rss"
    url = "/index.xml"
    weight = 4

[params]
    defaultTheme = "light"
    subtitle = "Faiz's notes on software development"
    description = "Faiz Mokhtar's notes on software development"
    copyright = "Be Nice"
    opengraph = true
    twitter_cards = true
    authorbox = true
    latestpostcount = 5
    post_navigation = true
    postSections = ["posts"]
    highlightColor = "#ea4c89" # Override highlight color
    post_meta = ["date", "categories", "translations"] # Order of post meta information
    dateFormatSingle = "02 Jan 2006"
    dateFormatList = "02 Jan 2006"

[params.widgets.social]
    twitter = "faizmokh"
    linkedin = "faizmokh"
    telegram = "@faizmokh"
    github = "faizmokhtar"
    email = "mfmokhtar@gmail.com"

[languages.en.params.logo]
    logoText = "./til"
    logoHomeLink = "/"