baseURL = "https://faizmokhtar.com/"
languageCode = "en-us"
title = "@faizmokh"
theme = "hugo-tania"
googleAnalytics = "UA-45192347-5"
copyright = "Copyright © 2021, Faiz Mokhtar."
pygmentsCodefences = true
pygmentsStyle = "pygments"

hideMadeWithLine = true
enableRobotsTXT = true

[[menu.header]]
    name = "Articles"
    url = "/articles/"
    weight = 1
[[menu.header]]
    name = "About me"
    url = "/about/"
    weight = 2

[[menu.footer]]
    name = "RSS"
    url = "/index.xml"

[params]
    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
    # favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    # images = ["images/share.png"]
    hideMadeWithLine = true
    title = "@faizmokh's blog"
    defaultTheme = "light"
    subtitle = "Faiz's notes on software development"
    description = "Faiz Mokhtar's notes on software development"
    copyright = "Be Nice"
    opengraph = true
    twitter_cards = true
    authorbox = true
    highlightColor = "#ea4c89" # Override highlight color
    post_meta = ["date", "categories", "translations"] # Order of post meta information
    dateFormatSingle = "02 Jan 2006"
    dateFormatList = "02 Jan 2006"

# to enable syntax highlighting
[markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 2
    noClasses = false