baseURL = "https://faizmokhtar.com/"
languageCode = "en-us"
title = "@faizmokh"
theme = "hugo-classic"
googleAnalytics = ""

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "rss"
    url = "/index.xml"


[params]
    description = "Collection of notes"
    footer = "&copy; Be nice."
